name: aimrelax_live
description: AIMRELAX LIVE - Android PUBG broadcaster
publish_to: 'none'
version: 2.1.0+3
environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.9.1
  permission_handler: ^12.0.1
  wakelock_plus: ^1.4.0
flutter:
  uses-material-design: true
