Run npx cap add android
  npx cap add android
  shell: /usr/bin/bash -e {0}
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/21.0.12-1/x64
    JAVA_HOME_21_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/21.0.12-1/x64
[error] Could not find installation of TypeScript.
        To use capacitor.config.ts files, you must install TypeScript in your project, e.g. w/ npm install -D typescript
Error: Process completed with exit code 1.
