name: Build AIMRELAX LIVE APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: flutter

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Check project
        run: |
          pwd
          ls -la
          test -f pubspec.yaml

      - name: Flutter pub get
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AIMRELAX-LIVE-APK
          path: flutter/build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
